version: "3.0"
services:
  sockets_server:
    build: .
    image: rafipayment_socket_server
    container_name: socket_server
    environment:
      - NODE_ENV=dev
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - rafipayment_certificate_data:/etc/letsencrypt
    command: tail -f /dev/null

volumes:
  rafipayment_certificate_data:
    external: true

networks:
  default:
    external:
      name: rafipayment_network

