version: "3.0"
services:
  sockets_server:
    build: .
    container_name: 'socket_server'
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - rafipayment_certificate_data:/etc/letsencrypt

volumes:
  rafipayment_certificate_data:
    external: true

networks:
  default:
    external:
      name: rafipayment_network

