version: "3.0"
services:
  socket_server:
    build: .
    image: rafipayment_socket_server
    container_name: socket_server
    environment:
      - NODE_ENV=staging
    ports:
      - 4200:4200
    volumes:
      - rafipayment_certificate_data:/etc/letsencrypt

volumes:
  rafipayment_certificate_data:
    external: true

networks:
  default:
    external:
      name: rafipayment_network

