version: "3.0"
services:
  sockets_server:
    build: .
    image: rafipayment_socket_server
    container_name: socket_server
    environment:
      - NODE_ENV=dev
      - FORCE_COLOR=1
    ports:
      - 4200:4200

networks:
  default:
    external:
      name: rafipayment_network
